# - Find WIRINGPI
# Find the native WIRINGPI includes and library
# This module defines
#  WIRINGPI_INCLUDE_DIR, where to find wiringPi.h, etc.
#  WIRINGPI_LIBRARIES, the libraries needed to use WIRINGPI.
#  WIRINGPI_FOUND, If false, do not try to use WIRINGPI.

FIND_PATH(WIRINGPI_INCLUDE_DIR wiringPi.h)

message(STATUS "Found wiringPi: ${WIRINGPI_INCLUDE_DIR}")


SET(WIRINGPI_NAMES ${WIRINGPI_NAMES} wiringPi)
FIND_LIBRARY(WIRINGPI_LIBRARY NAMES ${WIRINGPI_NAMES} )

# handle the QUIETLY and REQUIRED arguments and set WIRINGPI_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(WIRINGPI DEFAULT_MSG WIRINGPI_LIBRARY WIRINGPI_INCLUDE_DIR)

IF(WIRINGPI_FOUND)
  SET(WIRINGPI_LIBRARIES ${WIRINGPI_LIBRARY})
ENDIF(WIRINGPI_FOUND)

# Deprecated declarations.
#SET (NATIVE_JPEG_INCLUDE_PATH ${WIRINGPI_INCLUDE_DIR} )
#GET_FILENAME_COMPONENT (NATIVE_JPEG_LIB_PATH ${WIRINGPI_LIBRARY} PATH)

MARK_AS_ADVANCED(WIRINGPI_LIBRARY WIRINGPI_INCLUDE_DIR )
